before_script:
  - docker --version

stages:
  - build
  - test
  - deploy

build_image:
  stage: build
  script:
    - docker build -t docker-image .
  only:
    - master
  tags:
    - shell-docker

test_image:
  stage: test
  script:
    - docker run --rm docker-image ./gradlew test
  only:
    - master
  tags:
    - shell-docker

deploy_image:
  stage: deploy
  script:
    - docker tag docker-image vertigo/ci-test:$CI_BUILD_NAME
    - docker push vertigo/ci-test:$CI_BUILD_NAME
  only:
    - master
  tags:
    - shell-docker
